### ISSUE TITLE
Can PVmismatch package applied to Bifacial Modules ?

### ISSUE THREAD

**Issue by xjianwei520** [SunPower/PVMismatch#81]
Dear Sir : 
Recently, I try to apply PVmismatch Tool to Bifacial Modules Project By paralleling two cell which seeing as Front cell and Rear cell . actually , they are some one cell .  i got result , but VOC is not normal as  below 

![ss](https://user-images.githubusercontent.com/32535389/40601907-73e7d47c-6289-11e8-9ba7-ece0e847680b.png)

I want to know that can the PVmismatch tool update to support Bificial Module Application ?
Thank you

**Comment by chetan201** [comment]
Hi @xjianwei520,
Currently there is no specific feature for bi facial modules. But, it should be possible to approximate them using existing PVMismatch framework.
The plots aren't well visible here but at a first thought, with reduction in irradiance, the voltage reduces and that's what you are seeing. 

A simple approximation would be to scale the irradiance (suns) by the factor or extra gain because of back surface collection. 
Let's say 
Front cell = 1 sun
Back cell = 0.2 sun
then total cell = 1.2 sun

We will be working on adding the bifacial capability along the way but it's probably on a longer roadmap for the package.

**Comment by anomam** [comment]
Hi @xjianwei520 ,
Are you creating two different cells for front and back because you need different cell parameters for the two sides of the cell? Otherwise, I think that @chetan201 's approach would be worth trying.
By the way, I haven't seen many papers on this type of problem yet. Do you have any recommendation for a paper on this that we could use to improve PVMismatch @xjianwei520 ?

**Comment by xjianwei520** [comment]
Hi, @anomam 👍 
Yes, I used the different cells for front and back by different cell parameters from testing data in lab.
i saw a paper about using this way. maybe not more. 
<Investigations on albedo dependency of bifiacial PV yield >
<Modeling and analysis of a bifacial grid-connected photovoltaic system>

**Comment by xjianwei520** [comment]
1. Investigations on albedo dependency of bifacial pv yield
2. Modeling and analysis of  a bifacial grid-connected photovoltatic system

**Comment by anomam** [comment]
Sorry for the delayed reply @xjianwei520 , and thanks for your messages!
Unfortunately we don't have such a model in PVMismatch to my knowledge. 
@amir-asgharzadeh , do you know by any chance how national labs handle bifacial cell & module modeling when using different model parameters for front and back surfaces?

**Comment by amir-asgharzadeh** [comment]
To the best of my knowledge, there are some electrical models that you can use to model bifacial cells/modules given the front and back irradiance. For example, you can use the weighted 2-diode model which uses a 2-diode model for both front and rear IV characteristics of the module. These parameters can be different for front and back sides. Then, the IV curve for the module output is obtained from parameters scaled with the front and rear irradiance. The method is presented in "Outdoor performance of bifacial modules by measurements and modelling " by Gaby J.M. Janssen.
https://www.sciencedirect.com/science/article/pii/S187661021500819X

**Comment by mikofski** [comment]
considering Rhonda Bailey just did this at the [2018 NREL BifiPV workshop](http://bifipv-workshop.com/index.php?id=denver-2018-program) I think you can close this issue now, right?

**Comment by chetan201** [comment]
@xjianwei520 
Would you be able to email me your email address? I would like to gather some feedback regarding your usage of PVMismatch for some documentation.  Thanks!
Chetan.

**Comment by mikofski** [comment]
@chetan201 can't this issue be closed? I think Rhonda and Silvana already presented on this using pvmismatch.
