### ISSUE TITLE
Make PVMismatch Python 3 compatible

### ISSUE THREAD

**Issue by chetan201** [SunPower/PVMismatch#85]
2020 isn't too far. We need to bring PVMismatch into Python 3 world.

**Comment by mikofski** [comment]
Done already. PVMismatch has been Python 3 compatible since #54, Travis CI already checks for Python 3 compatibility with every push to master and every PR, and universal py2-py3 wheels are built on every release, so IMHO you can close this issue. But you may want to consider ending support for Python-2 eventually. See
https://github.com/SunPower/PVMismatch/pull/54

**Comment by chetan201** [comment]
haha! that's funny considering I approved the merge of that PR ;) 
Thanks for reminding me @mikofski !
